### ISSUE TITLE
I want more rights!

### ISSUE THREAD

**Issue by theo-armour** [haraldreingruber/pair-programming-with-theo-armour#2]
@haraldreingruber 

I want more rights!

* I would like to be able to set a tag for an issue
* Adjust settings such as enabling GitHub pages and seeing traffic reports
* Adding contributors
* Setting repo topics
* Committing may be even

And one day we can discuss setting up an organization for your pair-programming "alumni association"

**Comment by haraldreingruber** [comment]
Hi @theo-armour,

I think you need to accept the pending invitation. Did you receive an email from github?

![Screenshot_20200328-091830](https://user-images.githubusercontent.com/3355284/77818755-626ee080-70d5-11ea-8c5a-1cdd729f67cf.png)

**Comment by theo-armour** [comment]
Looks like I went straight to the repo without clicking the "accept" button first.

**Comment by haraldreingruber** [comment]
No problem.
